language: node_js

node_js:
- '12.18.3'

os:
- linux

group: dev
sudo: required
dist: bionic

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/

env:
  global:
    - RELEASE_TAG_EXPRESSION=^v?[0-9]+\.[0-9]+\.[0-9]+$

install:
- npm install

script:
- npm run test
- npm run package

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME == linux"
  - provider: script
    script: npx vsce publish -p $VSCE_TOKEN --packagePath *.vsix
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_EXPRESSION"
  - provider: script
    script: npx ovsx publish *.vsix -p $OVSX_TOKEN
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ $RELEASE_TAG_EXPRESSION"

cache:
  directories:
    - node_modules